name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '17', '21' ]
        distribution: [ 'zulu', 'temurin', 'adopt-openj9', 'semeru', 'jetbrains', 'adopt-hotspot' ]
        include:
          - version: '17.0.4'
            distribution: 'semeru'
          - version: '17.0.5'
            distribution: 'semeru'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.distribution }}

    - name: Build with Gradle Wrapper
      run: ./gradlew test
